[project]
name = "ansible-infrastructure"
version = "0.1.0"
description = "Ansible infrastructure for my personal projects"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ansible>=12.2.0",
    "ansible-core>=2.19.4",
    "ansible-lint>=25.11.1",
]
