---
- name: Ensure base packages installed
  package:
    name: {{ base_packages }}
    state: present

- name: Deploy bashrc
  copy:
    src: bashrc
    dest: ~/.bashrc
    mode: '0644'
  notify: restart shell env

- name: Deploy vimrc
  copy:
    src: vimrc
    dest: ~/.vimrc
    mode: '0644'
